# Generated by Django 4.2.27 on 2026-03-31 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0004_sale"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("address", models.TextField()),
            ],
        ),
    ]
